### ISSUE TITLE
Initial Data Modeling

### ISSUE THREAD

**Issue by Henrique-182** [HSR-Pet/psystem#4]
# Entities

1. Produto

2. Compra

3. Itens_Compra

4. Fornecedor

5. Endereco_Fornecedor

6. Pedido

7. Itens_Pedido

8. Parcelas

9. Usuario

10. Vendedor

# Relationships
Fornecedor (1-1) Endereco_Fornecedor

Fornecedor (1-N) Compra 

Compra (1-N) Itens_Compra (N-1) Produtos

Pedido (1-N) Itens_Pedido (N-1) Produto

Pedido (1-N) Parcelas

Pedido (1-1) Vendedor

# Attributes
Produto
> Id
> Nome
> Descrição
> Preço
> Local Estoque
> Código de Barras
> NCM
> Quantidade Em Estoque
> Unidade Vendida
> Unidade Comprada

Fornecedor
> Id
> Nome Fantasia
> Razão Social
> CNPJ/CPF
> Inscrição Estadual / RG
> Inscrição Municipal
> Telefone
> Celular
> E-mail
> Pessoa

Endereco_Fornecedor
> Id
> País
> Estado
> Município
> CEP
> Bairro
> Logradouro
> Número
> Complemento

Pedido 
> Id
> Chave Estrangeira de Cliente
> Chave Estrangeira de Vendedor
> Data e Hora Emissão
> Data e Hora Entrega
> Total Bruto
> Total Desconto
> Valor Final
> Informações Adicionais

Itens_Pedido
> Id
> Chave Estrangeira de Pedido
> Chave Estrangeira de Produto
> Quantidade 
> Unidade
> Valor Unitário
> Valor Final
> Desconto (R$)

Parcelas
> Id
> Chave Estrangeira de Pedido
> Valor
> Porcentagem em Relação ao Total do Pedido (?)
> Número da Parcela
> Está Paga
> Forma de Pagamento (pix, dinheiro)
> Dia Vencimento

# Constraints

**Comment by Sam00dev** [comment]
Guei

Em dom., 9 de jul. de 2023 09:30, Henrique Lobo ***@***.***>
escreveu:
